import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "staging", "production"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodString;
    JWT_ACCESS_SECRET: z.ZodString;
    JWT_REFRESH_SECRET: z.ZodString;
    ACCESS_TOKEN_TTL: z.ZodDefault<z.ZodString>;
    REFRESH_TOKEN_TTL_DAYS: z.ZodDefault<z.ZodNumber>;
    TYPESENSE_HOST: z.ZodString;
    TYPESENSE_PORT: z.ZodDefault<z.ZodNumber>;
    TYPESENSE_PROTOCOL: z.ZodDefault<z.ZodEnum<["http", "https"]>>;
    TYPESENSE_API_KEY: z.ZodString;
    PAYSTACK_SECRET_KEY: z.ZodString;
    PAYSTACK_WEBHOOK_SECRET: z.ZodString;
    OPENAI_API_KEY: z.ZodString;
    S3_REGION: z.ZodString;
    S3_BUCKET: z.ZodString;
    S3_ACCESS_KEY_ID: z.ZodString;
    S3_SECRET_ACCESS_KEY: z.ZodString;
    CORS_ORIGIN: z.ZodDefault<z.ZodString>;
    ADMIN_DASHBOARD_URL: z.ZodDefault<z.ZodString>;
    API_BASE_URL: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "staging" | "production";
    PORT: number;
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_ACCESS_SECRET: string;
    JWT_REFRESH_SECRET: string;
    ACCESS_TOKEN_TTL: string;
    REFRESH_TOKEN_TTL_DAYS: number;
    TYPESENSE_HOST: string;
    TYPESENSE_PORT: number;
    TYPESENSE_PROTOCOL: "http" | "https";
    TYPESENSE_API_KEY: string;
    PAYSTACK_SECRET_KEY: string;
    PAYSTACK_WEBHOOK_SECRET: string;
    OPENAI_API_KEY: string;
    S3_REGION: string;
    S3_BUCKET: string;
    S3_ACCESS_KEY_ID: string;
    S3_SECRET_ACCESS_KEY: string;
    CORS_ORIGIN: string;
    ADMIN_DASHBOARD_URL: string;
    API_BASE_URL: string;
}, {
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_ACCESS_SECRET: string;
    JWT_REFRESH_SECRET: string;
    TYPESENSE_HOST: string;
    TYPESENSE_API_KEY: string;
    PAYSTACK_SECRET_KEY: string;
    PAYSTACK_WEBHOOK_SECRET: string;
    OPENAI_API_KEY: string;
    S3_REGION: string;
    S3_BUCKET: string;
    S3_ACCESS_KEY_ID: string;
    S3_SECRET_ACCESS_KEY: string;
    NODE_ENV?: "development" | "test" | "staging" | "production" | undefined;
    PORT?: number | undefined;
    ACCESS_TOKEN_TTL?: string | undefined;
    REFRESH_TOKEN_TTL_DAYS?: number | undefined;
    TYPESENSE_PORT?: number | undefined;
    TYPESENSE_PROTOCOL?: "http" | "https" | undefined;
    CORS_ORIGIN?: string | undefined;
    ADMIN_DASHBOARD_URL?: string | undefined;
    API_BASE_URL?: string | undefined;
}>;
export type AppEnv = z.infer<typeof envSchema>;
export declare const parseEnv: (input: NodeJS.ProcessEnv) => AppEnv;
export declare const appConstants: {
    readonly apiPrefix: "api/v1";
    readonly maxAudioUploadBytes: number;
    readonly acceptedAudioMimeTypes: readonly ["audio/mpeg", "audio/mp3", "audio/wav", "audio/x-wav", "audio/mp4", "audio/aac", "audio/flac", "audio/ogg"];
    readonly accessTokenCookie: "wc_at";
    readonly refreshTokenCookie: "wc_rt";
};
export {};
//# sourceMappingURL=index.d.ts.map